width: 400
height: 400
# Perlin: 0; Simplex: 1; Open: 2; Cellular: 3; FBM: 4.
# CONTINENTALNESS
continentalness.noise: 0
continentalness.amplitude: 10
continentalness.octaves: 2
continentalness.frequency: .01
# PICK AND VALLEY
pickNvalley.noise: 0
pickNvalley.amplitude: 40
pickNvalley.octaves: 6
pickNvalley.frequency: .015
pickNvalley.elevation: 2.5
# EROSION
erosion.noise: 0
erosion.amplitude: 5
erosion.octaves: 2
erosion.frequency: .01
# TEMPERATURE
temperature.noise: 0
temperature.octaves: 2
temperature.frequency: .01
# HUMIDITY
humidity.noise: 0
humidity.octaves: 2
humidity.frequency: .01
#
data.path: ../data/
data.extension: ply
refine: 0
logging.file: ../main.log 
logging.level: INFO