width: 1000
height: 1000
amplitude: 50
octaves: 4
frequency: .01
noise: 0
continentalness: 1
pickNvalley: 2
erosion: 2
data.path: ../data/
data.extension: ply
refine: 0
logging.file: ../main.log 
logging.level: INFO