width: 1600
height: 1600
# Perlin: 0; Simplex: 1; Open: 2; Cellular: 3; FBM: 4.
#
data.path: ../data/
data.extension: ply
data.withTexture: 1
data.mtl: ../data/biomi.mtl
assets.tree: ../assets/trees_placeholder90.obj
logging.file: ../main.log 
logging.level: INFO