width: 700
height: 700
# Perlin: 0; Simplex: 1; Open: 2; Cellular: 3; FBM: 4.
# CONTINENTALNESS
continentalness: 0
cAmplitude: 10
cOctaves: 2
cFrequency: .01
# PICK AND VALLEY
pickNvalley: 0
pvAmplitude: 50
pvOctaves: 10
pvFrequency: .01
elevation: 2
# EROSION
erosion: 0
eAmplitude: 5
eOctaves: 2
eFrequency: .01
# TEMPERATURE
temperature: 0
tOctaves: 2
tFrequency: .005
# HUMIDITY
humidity: 0
hOctaves: 2
hFrequency: .005
#
data.path: ../data/
data.extension: ply
refine: 0
logging.file: ../main.log 
logging.level: INFO