width: 400
height: 400
# Perlin: 0; Simplex: 1; Open: 2; Cellular: 3; FBM: 4.
# CONTINENTALNESS
continentalness: 0
cAmplitude: 10
cOctaves: 2
cFrequency: .01
# PICK AND VALLEY
pickNvalley: 0
pvAmplitude: 40
pvOctaves: 6
pvFrequency: .015
elevation: 2.5
# EROSION
erosion: 0
eAmplitude: 5
eOctaves: 2
eFrequency: .01
# TEMPERATURE
temperature: 0
tOctaves: 2
tFrequency: .01
# HUMIDITY
humidity: 0
hOctaves: 2
hFrequency: .01
#
data.path: ../data/
data.extension: ply
refine: 0
logging.file: ../main.log 
logging.level: INFO
# ulteriori
continentalness.amplitude: 1
continentalness.octaves: 1
continentalness.frequency: 1
continentalness.noise: 1
continentalness.elevation: 1
